name: Deploy Node App to EC2

on:
  worklow_dispath:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy code to EC2 via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "."
          target: "/home/ubuntu/Travelmemory"  

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Install Node.js and PM2 if not installed
            if ! command -v node > /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt-get install -y nodejs
              #sudo npm install -g pm2
            fi

            # Set up environment variables
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" > ~/Travelmemory/backend/.env
            echo "PORT=3001" >> ~/Travelmemory/backend/.env
            # Install dependencies and start the app
            cd ~/Travelmemory/backend
            npm install
            cd ../frontend
            pub_ip=`curl http://checkip.amazonaws.com`
            echo "REACT_APP_BACKEND_URL=http://"$pub_ip":3001" > .env
            npm install
            # Start or restart the app with PM2
            cd ../backend
            nohup node index.js > nodejs.log 2>&1 &
            cd ../frontend
            nohup npm start > react.log 2>&1 &
