name: SCP Upload to EC2

on:
  push:
    branches: [main]  # or any branch you want to trigger deployment

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload project to EC2 via SCP
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "."                      # current directory
        target: "/home/ubuntu/Travelmemory"      # remote EC2 directory
